// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PlantNursary.DataAccess;

#nullable disable

namespace PlantNursary.DataAccess.Migrations
{
    [DbContext(typeof(NursaryContext))]
    [Migration("20231128080847_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PlantNursary.Entities.Bed", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BreedingSectorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BreedingSectorId");

                    b.ToTable("beds");
                });

            modelBuilder.Entity("PlantNursary.Entities.BreedingSector", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("breedings");
                });

            modelBuilder.Entity("PlantNursary.Entities.Field", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("fields");
                });

            modelBuilder.Entity("PlantNursary.Entities.GreenHouse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("greenHouses");
                });

            modelBuilder.Entity("PlantNursary.Entities.Line", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SectorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int[]>("events")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.HasKey("Id");

                    b.HasIndex("SectorId");

                    b.ToTable("lines");
                });

            modelBuilder.Entity("PlantNursary.Entities.Nursary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("nurses");
                });

            modelBuilder.Entity("PlantNursary.Entities.Plant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("BirthDay")
                        .HasColumnType("date");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LineId")
                        .HasColumnType("uuid");

                    b.Property<string>("Peculiarities")
                        .HasColumnType("text");

                    b.Property<Guid?>("ReservationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("diameter")
                        .HasColumnType("integer");

                    b.Property<int>("groundType")
                        .HasColumnType("integer");

                    b.Property<int>("hardinessType")
                        .HasColumnType("integer");

                    b.Property<int>("height")
                        .HasColumnType("integer");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("placeType")
                        .HasColumnType("integer");

                    b.Property<int>("plantType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LineId");

                    b.HasIndex("ReservationId");

                    b.ToTable("plants");
                });

            modelBuilder.Entity("PlantNursary.Entities.QueenCell", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("QueenCells");
                });

            modelBuilder.Entity("PlantNursary.Entities.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("reservations");
                });

            modelBuilder.Entity("PlantNursary.Entities.Sector", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FieldId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FieldId");

                    b.ToTable("sectors");
                });

            modelBuilder.Entity("PlantNursary.Entities.Bed", b =>
                {
                    b.HasOne("PlantNursary.Entities.BreedingSector", null)
                        .WithMany("beds")
                        .HasForeignKey("BreedingSectorId");
                });

            modelBuilder.Entity("PlantNursary.Entities.Line", b =>
                {
                    b.HasOne("PlantNursary.Entities.Sector", null)
                        .WithMany("Lines")
                        .HasForeignKey("SectorId");
                });

            modelBuilder.Entity("PlantNursary.Entities.Plant", b =>
                {
                    b.HasOne("PlantNursary.Entities.Line", null)
                        .WithMany("plants")
                        .HasForeignKey("LineId");

                    b.HasOne("PlantNursary.Entities.Reservation", null)
                        .WithMany("plants")
                        .HasForeignKey("ReservationId");
                });

            modelBuilder.Entity("PlantNursary.Entities.Sector", b =>
                {
                    b.HasOne("PlantNursary.Entities.Field", null)
                        .WithMany("sectors")
                        .HasForeignKey("FieldId");
                });

            modelBuilder.Entity("PlantNursary.Entities.BreedingSector", b =>
                {
                    b.Navigation("beds");
                });

            modelBuilder.Entity("PlantNursary.Entities.Field", b =>
                {
                    b.Navigation("sectors");
                });

            modelBuilder.Entity("PlantNursary.Entities.Line", b =>
                {
                    b.Navigation("plants");
                });

            modelBuilder.Entity("PlantNursary.Entities.Reservation", b =>
                {
                    b.Navigation("plants");
                });

            modelBuilder.Entity("PlantNursary.Entities.Sector", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
